### ISSUE TITLE
Build broken on Windows

### ISSUE THREAD

**Issue by isovector** [neovimhaskell/nvim-hs#100]
As part of Cornelis' new CI infrastructure (thanks @malob!), we're seeing the following build failure on windows:

```
nvim-hs                          > [14 of 28] Compiling Neovim.RPC.Common
nvim-hs                          > 
nvim-hs                          > library\Neovim\RPC\Common.hs:91:18: error:
nvim-hs                          >     * Variable not in scope: getSocketUnix :: FilePath -> IO Socket
nvim-hs                          >     * Perhaps you meant `getSocketUDP' (imported from Data.Streaming.Network)
nvim-hs                          >    |
nvim-hs                          > 91 |         liftIO $ getSocketUnix f >>= flip socketToHandle ReadWriteMode
nvim-hs                          >    |     
```

**Comment by saep** [comment]
I'll have to figure out which kinds of connections are supported for Neovim on Windows.

In theory, Windows 10 and onwards should support Unix Sockets and so Neovim might support them as well. However, streaming-commons has an ifdef to not include that functionality on windows.

**Comment by saep** [comment]
I've tried a quick fix and noticed that the code generation from `nvim --api-info` doesn't work on windows. So, this has become even more complicated to fix. :-(

**Comment by saep** [comment]
It should build and work on Windows with a version equal to or newer than https://hackage.haskell.org/package/nvim-hs-2.3.0.0

**Comment by isovector** [comment]
Amazing, thanks!
