### ISSUE TITLE
NVIM_LISTEN_ADDRESS may no longer exist

### ISSUE THREAD

**Issue by saep** [neovimhaskell/nvim-hs#101]
I was remined by #100 that the environment variable `NVIM_LISTEN_ADDRESS` has been removed or changed its meaning. This may mean that `nvim-hs` no longer automatically connects to neovim on newer versions or the current dev version.

**Comment by justinmk** [comment]
Nvim sets $NVIM in child jobs. For telling nvim itself where to listen, the `nvim --listen` arg is preferred. For cases where a `--listen` arg can't be passed to `nvim`, you can still use `$NVIM_LISTEN_ADDRESS`.

The reason for the change was that `$NVIM_LISTEN_ADDRESS` had conflicting purposes which made correct behavior impossible.
