### ISSUE TITLE
No instance for (NFData Object)

### ISSUE THREAD

**Issue by teto** [neovimhaskell/nvim-hs#50]
I've been trying to `nvim-hs$ cabal install . ` the current master c0c98b but it gives:
`library/Neovim/Classes.hs|313 col 10 error| No instance for (NFData Object) arising from the superclasses of an instance declarationIn the instance declaration for ‘NvimObject Object’ [1 of 5] Compiling CabalHelper.Types ( CabalHelper/Types.hs, /home/teto/.ghc-mod/cabal-helper/CabalHelper/Types.o )
`
Here is ghc -v
```
Glasgow Haskell Compiler, Version 7.10.3, stage 2 booted by GHC version 7.10.3
Using binary package database: /usr/lib/ghc/package.conf.d/package.cache
Using binary package database: /home/teto/.ghc/x86_64-linux-7.10.3/package.conf.d/package.cache
wired-in package ghc-prim mapped to ghc-prim-0.4.0.0-6cdc86811872333585fa98756aa7c51e
wired-in package integer-gmp mapped to integer-gmp-1.0.0.0-3c8c40657a9870f5c33be17496806d8d
wired-in package base mapped to base-4.8.2.0-0d6d1084fbc041e1cded9228e80e264d
wired-in package rts mapped to builtin_rts
wired-in package template-haskell mapped to template-haskell-2.10.0.0-3c4cb52230f347282af9b2817f013181
wired-in package ghc mapped to ghc-7.10.3-624693c6aa854116c707bc7b4d0d7cb6
wired-in package dph-seq not found.
wired-in package dph-par not found.
```
As master is not a stable version feel free to ignore this issue, I was jsut surprised to see the "Build passing" badge.

**Comment by saep** [comment]
I probably forgot to add a proper version bound to the messagepack dependency. I'll have a look at this this weekend.

**Comment by teto** [comment]
it fixed it thanks
