### ISSUE TITLE
nvim-hs is in stackage - update README

### ISSUE THREAD

**Issue by lancelet** [neovimhaskell/nvim-hs#59]
It seems that `nvim-hs-0.2.2` is [now in stackage](https://www.stackage.org/lts-9.0/package/nvim-hs-0.2.2).

AFAICT, as a result, the README could be updated to simplify the installation instructions that use stack.

**Comment by lancelet** [comment]
Addressed by PR #60.

**Comment by saep** [comment]
I will update the rest and test the instructions. The documentation update was on my mental list for a few weeks, but I wasn't really motivated to do so. Thanks for forcing me a bit. :-)
