### ISSUE TITLE
Question: Why `MonadCatch` instance is removed?

### ISSUE THREAD

**Issue by Hogeyama** [neovimhaskell/nvim-hs#64]
Hi, thank you for awesome package!
In [this line of this commit](https://github.com/neovimhaskell/nvim-hs/commit/9de00b73f182f3ae093e557c017a341eda3f2442#diff-fbbe19dcf8aa022bf5a843bd2df2994fL63), `MonadCatch` and `MonadMask` instances of `Neovim` are removed. What is the purpose of this?

**Comment by saep** [comment]
I'm glad that someone likes and uses this package! :-)

After reading some blog posts about the difficulty of exception handling and alike, I thought it would be a good idea to simplify things and use a library that does the heavy lifting. The obvious candidate for me was the [unliftio](https://hackage.haskell.org/package/unliftio) package. The package description explains the rationales and tradeoffs of the approach and I encourage you to read it if you're interested in the details.

If you have problems with a piece of code you wrote, I'm happy to help you out.

 As there have been no new features compared to the previous version (0.2.5), there is no rush to change your code to use the new version. The exception handling has been improved though, which I find a bit funny considering the nature of this ticket. :-)

**Comment by Hogeyama** [comment]
Oh, so I should just import `UnliftIO.Exception` instead of `Control.Exception`(`.Safe`).
The unliftio package seems interesting. I'll read it. Thank you!
