### ISSUE TITLE
add again to stackage

### ISSUE THREAD

**Issue by saep** [neovimhaskell/nvim-hs#68]
- [x] Wait for rodrigosetti/messagepack/pull/12 to be merged
- [x] Open PR on stackage

**Comment by chris-bacon** [comment]
Hi @saep, just wondering if I can I help with moving this forward or are you waiting on anything in particular?

**Comment by saep** [comment]
I did a PR for the messagepack dependency yesterday and wanted for that to land first. I planned to do it for nvim-hs and nvim-hs-contrib this evening.

**Comment by chris-bacon** [comment]
Awesome! Really looking forward to using this! :+1:
