### ISSUE TITLE
Hangs without showing any error messages

### ISSUE THREAD

**Issue by Hogeyama** [neovimhaskell/nvim-hs#79]
## Description

`nvim-hs` plugin gets unresponsive without showing any error message when it evaluates an expression like `vim_command undefined`. To reproduce, just run `debug' (vim_command undefined)` in ghci repl.

## Cause

When it evaluates `vim_command undefined`, the `undefined` is wrapped in `FunctionCall` message at `Neovim.RPC.FunctionCall.acall`, and written in `eventQueue`. The event handler reads the message and evaluates it, and thus dies.

## Possible solution

It can be solved by evaluating the function parameters before inserting into `eventQueue`:

```haskell
acall :: (NvimObject result)
     => FunctionName
     -> [Object]
     -> Neovim env (STM (Either NeovimException result))
acall fn parameters = do
    evaluate (rnf parameters) -- impure exception founds here
    q <- Internal.asks' Internal.eventQueue
    mv <- liftIO newEmptyTMVarIO
    timestamp <- liftIO getCurrentTime
    atomically' . writeTQueue q . SomeMessage $ FunctionCall fn parameters mv timestamp
    return $ convertObject <$> readTMVar mv
```

Altenatively, it may be better to write a wrapper of `writeTQueue` though it requires `NFData` as subclass of `Message`.

```haskell
writeMessage :: (MonadIO m, Message message) => TQueue SomeMessage -> message -> m ()
writeMessage q message = liftIO $ do
    evaluate (rnf message)
    atomically $ writeTQueue q (SomeMessage message)
```

I'll make a PR if you don't mind.

**Comment by saep** [comment]
A PR would be great! 
The proposed changes look good to me.
