### ISSUE TITLE
Add to Latest Stackage?

### ISSUE THREAD

**Issue by smolck** [neovimhaskell/nvim-hs#87]
Hello! (I'd like to preface this by saying that I'm still pretty new to Haskell, so I apologize if my understanding is wrong here.)

After looking on Stackage, it seems nvim-hs isn't part of the latest LTS (https://www.stackage.org/lts-16.4/hoogle?q=nvim-hs) and I was wondering if it could be added (through a PR to stackage or however that works)? I guess LTS 14.27 was the last LTS that had nvim-hs, so would it be possible to update that?

**Comment by saep** [comment]
Hey! I created a pull request https://github.com/commercialhaskell/stackage/pull/5503, it should be in one of the next nightly snapshots and in the next major LTS release. Until then, you'll have to add nvim-hs to the the extra-deps of you `stack.yaml`. One of the following entries should work. If you have any issues, I'm happy to help.
```yaml
extra-deps:
#- nvim-hs-2.1.0.3
- nvim-hs-2.1.0.4
```

**Comment by saep** [comment]
It's in the latest SNAPSHOT now https://www.stackage.org/nightly-2020-07-12/package/nvim-hs-2.1.0.4

Can I close this?

**Comment by smolck** [comment]
Awesome! Thanks!

And yeah; I’ll go ahead and close this.
