### ISSUE TITLE
Exception not caught: broken cached binary path file

### ISSUE THREAD

**Issue by locallycompact** [neovimhaskell/nvim-hs#92]
Also getting this when I open vim

```
Error detected while processing function nvimhs#start[2]..<SNR>11_readCachedBinPaths:
line    9:
E605: Exception not caught: broken cached binary path file
Error detected while processing function nvimhs#start:
line    2:
E171: Missing :endif
```

**Comment by saep** [comment]
Probably caused by #91

**Comment by saep** [comment]
If this still happens with the latest version (2.1.0.7 or master) , please tell me how to reproduce this.

**Comment by saep** [comment]
I'm closing this because I cannot reproduce this and no additional information has been provided for over a year.
